FROM python:3.10-slim-buster

RUN apt-get update

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

ENV HOST 0.0.0.0
ENV PORT 4000
ENV DEBUG true

COPY . /api/main
WORKDIR /api/main

RUN pip install -U setuptools pip
RUN pip install -r requirements.txt

EXPOSE 4000

RUN pip install gunicorn

CMD ["gunicorn", "--bind", "0.0.0.0:4000", "--workers", "3", "app:app"]